name: detect runtime error

on:
  schedule:
    - cron: '0 22 * * *'
jobs:
  detectError:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./apps/image-editor
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: create config variable
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          node createConfigVariable.js
      - name: set global error variable
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          errorVariable=`cat ./errorVariable.txt`
          echo "ERROR_VARIABLE=$errorVariable" >> $GITHUB_ENV
      - name: set url
        working-directory: ${{ env.WORKING_DIRECTORY }}
        shell: bash
        run: |
          url=`cat ./url.txt`
          echo "URLS=$url" >> $GITHUB_ENV
      - name: detect runtime error
        uses: nhn/toast-ui.detect-runtime-error-actions@v1.0.1
        with:
          global-error-log-variable: ${{ env.ERROR_VARIABLE }}
          urls: ${{ env.URLS }}
        env:
          BROWSERSTACK_USERNAME: ${{secrets.BROWSERSTACK_USERNAME}}
          BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
