name: Publish docs
on: [workflow_dispatch]

env:
  BUILD_CACHE_KEY: ${{ github.sha }}

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install dependencies
        id: cache-keys
        uses: ./.github/composite-actions/install-dependencies
    outputs:
      root_cache_key: ${{ steps.cache-keys.outputs.root_cache_key }}

  build:
    name: Build package using cache
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: production
      - name: build
        uses: ./.github/composite-actions/build-package
        with:
          ROOT_CACHE_KEY: ${{ needs.install-dependencies.outputs.root_cache_key }}
          BUILD_CACHE_KEY: ${{ env.BUILD_CACHE_KEY }}
    outputs:
      root_cache_key: ${{ needs.install-dependencies.outputs.root_cache_key }}

  publish-docs:
    needs: [build]
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: production
      - name: Publish docs
        uses: ./.github/composite-actions/publish-docs
        with:
          ROOT_CACHE_KEY: ${{ needs.build.outputs.root_cache_key }}
          BUILD_CACHE_KEY: ${{ env.BUILD_CACHE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
